### ISSUE TITLE
Help to build GEOSgcm on a new server

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm#446]
Hi @mathomp4,

Would you please help (**provide instructions**) @gmao-cda build:
- baselibs
- GEOSgcm

on `measures1.umd.edu` @gmao-cda is going to provide a list of compilers and libraries he currently has. Thanks a lot for the help!

**Comment by mathomp4** [comment]
@sanAkel I can give it a try. I'll need to know what compilers and MPI stacks they have. If they are new enough, it should be doable...unless that machine is a weird one.

**Comment by gmao-cda** [comment]
Hi @mathomp4 , 

Thank you for the help! 
Below is the server info:
- Hardware: 
   - CPU: Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz. (8 cores)
   - 8GB RAM
   - 4TB free space shared by users
- Software:
   - OS: Red Hat Enterprise Linux Server release 7.9 (Maipo). 
   - GNU compiler (gcc/g++/gfortran) gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
   - No MPI installed.

**Comment by mathomp4** [comment]
Oooh boy. Yeah, you'll need to install GCC 11.3.0 or 12.1.0 on the machine. And then Open MPI built by that compiler. 

You might be able to install GCC 11/12 with the RHEL package manager but 7.9 is old enough that you might have to build it yourself. As for MPI, build that yourself as well as I never really trust MPI stacks from vendors. Better to build your own.

**Comment by gmao-cda** [comment]
@mathomp4 
Thanks for your guidance! 
I will try to first install gcc and Open MPI first.

Do you know which branch (commits) of baselibs and GEOSgcm should I build on?


I previously had fortune to build the following packages on my home Desktop as my warm-up workout:
- System info:
        - Ubuntu 20.04 LTS (Linux_x86) + gnu version 11.2.0 (gcc, gfortran, g++) + openmpi 4.1.2
- GEOS package info:
        - EMSA-baselibs v6.2.14 [[3b3c1e4](https://github.com/GEOS-ESM/ESMA-Baselibs/commit/3b3c1e4eca59d0779f1f046968c9517596653e10)]
        - mepo [[1310b69](https://github.com/GEOS-ESM/mepo/commit/1310b69701b7dc3217b5bf8c46f1d187ef323f73)]
        - GEOSgcm tag: v10.22.3 [[8e8c40c](https://github.com/GEOS-ESM/GEOSgcm/commit/8e8c40c97329c7eff8f5d836419d24adc52ab7fd)]

It seems when I install the full version of ESMA (make install ESMF_COMM=openmpi), I need to tweak a little bit on my local machine.
The main problem I met was: EMSA-baselibs v6.2.4 does not include lib `expat`, which is required by `udunits2`, and `udunits2` is required by `cdo`. I tweaked a little bit to install it.

I documented the whole installation process at https://github.com/cd10kfsu/GEOSgcm/wiki/Install-GEOS-GCM

**Comment by mathomp4** [comment]
If you are going to build it, I say go for the latest:

* Baselibs v7.5.0
* mepo `main` or latest tag (I think it's v1.45.0)
* GEOSgcm v10.22.5

As for `expat` I'd do something different and just...not build it! You can get Baselibs and build as:

```
make install ESMF_COMM=openmpi BUILD=ESSENTIALS
```
This gets you the "essentials" of Baselibs. Many of the libraries are built for other reasons around GEOS, but you shouldn't need them. Maybe the one extra I can see as useful is `nccmp` but that can be built later. (Now, if you do need `cdo` then you have to do the expat fun. Though you should be able to get it from RPM/Yum/whatever RHEL is using now.)

**Comment by sanAkel** [comment]
Thank you @mathomp4. 

On the `cdo` I have not used in a few years. I used to rely on it few years ago until I made friends with [xarray](https://docs.xarray.dev/en/stable/) and [xesmf](https://xesmf.readthedocs.io/en/latest/)!

**Comment by gmao-cda** [comment]
I started building gcc 11.3, got the following error:

configure: error: Building GCC requires GMP 4.2+, MPFR 3.1.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  Source code for these libraries can be found at
their respective hosting sites as well as at
https://gcc.gnu.org/pub/gcc/infrastructure/.  See also
http://gcc.gnu.org/install/prerequisites.html for additional info.  If
you obtained GMP, MPFR and/or MPC from a vendor distribution package,
make sure that you have installed both the libraries and the header
files.  They may be located in separate packages.

It seems I need to build a lot from scratch.
Will keep you updated.
Thank you!

**Comment by gmao-cda** [comment]
Luther at ESSIC helped me build the gnu version 8.3.1, and openmpi 3.1.3 on the server. He confirmed it is not possible for him to build gnu compiler version 11.3 or 12.0 through RHEL package manager.

**Comment by mathomp4** [comment]
@gmao-cda Those prereqs are in the GCC source. For example, to build GCC 12.1 you can do:
```
wget https://mirrors.concertpass.com/gcc/releases/gcc-12.1.0/gcc-12.1.0.tar.xz
tar xf gcc-12.1.0.tar.xz
cd gcc-12.1.0
./contrib/download_prerequisites
cd ..
mkdir BUILD-gcc-12.1.0 && cd BUILD-gcc-12.1.0
../gcc-12.1.0/configure --prefix=/path/to/where/you/want/gcc-gfortran/12.1.0 --enable-languages=c,c++,fortran |& tee configure.log
make -j4 |& tee make.log
make install |& tee makeinstall.log
```
I think that should work

**Comment by mathomp4** [comment]
Then for Open MPI 4.1.4 something like:

```
mkdir build-gcc-gfortran-12.1.0
cd build-gcc-gfortran-12.1.0
../configure CC=gcc CXX=g++ FC=gfortran --prefix=/path/to/where/you/want/gcc-gfortran-12.1.0/openmpi/4.1.4 |& tee configure.gcc-gfortran-12.1.0.log
mv config.log config.gcc-gfortran-12.1.0.log
make -j4 |& tee make.gcc-gfortran-12.1.0.log
make install |& tee makeinstall.gcc-gfortran-12.1.0.log
make check |& tee makecheck.gcc-gfortran-12.1.0.log
```

**_BUT_** you want to make sure the `gcc`, `g++` and `gfortran` are the ones you just built. So either put them in your PATH first or you'll need to use `gcc-12`, `g++-12`, and `gfortran-12` and then be careful to do so ever after. You can write a modulefile to make that easier.

**Comment by gmao-cda** [comment]
Thank you very much @mathomp4 ! your script is so clear.

I added the flag `--disable-multilib` when building gcc-12.1.0, due to this error message when `configure`

**Comment by gmao-cda** [comment]
finish building GNU 12.1.0 (build duration: 2hours).

**Comment by gmao-cda** [comment]
Finish building open MPI 4.1.4.
also built cmake-3.24.0, since no cmake on the current system.
(built duration: 58 min)

**Comment by gmao-cda** [comment]
Finish building EMSA-baselibs v7.5.0
```
git clone --recurse-submodules -b v7.5.0 https://github.com/GEOS-ESM/ESMA-Baselibs.git
make install ESMF_COMM=openmpi BUILD=ESSENTIALS
```

-------+---------+---------+--------------
Config | Install |  Check  |   Package
-------+---------+---------+--------------
  --   |   --    |   --    | antlr2
  --   |   --    |   --    | gsl
  ok   |   ok    |   --    | jpeg
  ok   |   ok    |   --    | zlib
  ok   |   ok    |   --    | szlib
  --   |   --    |   --    | curl
  ok   |   ok    |   --    | hdf4
  ok   |   ok    |   --    | hdf5
  ok   |   ok    |   --    | netcdf
  ok   |   ok    |   --    | netcdf-fortran
  --   |   --    |   --    | netcdf-cxx4
  --   |   --    |   --    | udunits2
  --   |   --    |   --    | nco
  --   |   --    |   --    | cdo
  --   |   --    |   --    | nccmp
  ok   |   ok    |   --    | esmf
  ok   |   ok    |   --    | xgboost
  ok   |   ok    |   --    | GFE
  ok   |   ok    |   --    | FLAP
  --   |   --    |   --    | hdfeos
  --   |   --    |   --    | hdfeos5
  --   |   --    |   --    | SDPToolkit
-------+---------+---------+--------------

**Comment by gmao-cda** [comment]
encountered error when using `mepo clone`:
mepo version: `git clone https://github.com/GEOS-ESM/mepo.git`

The error messages are:
```
(cda_suite) [cda@measures1 GEOSgcm]$ mepo clone
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | -d | <branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
   or: git remote set-branches [--add] <name> <branch>...
   or: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>

    -v, --verbose         be verbose; must be placed before a subcommand


Traceback (most recent call last):
  File "/data2/cda/model/mepo/mepo.d/command/clone/clone.py", line 59, in run
    allcomps = MepoState.read_state()
  File "/data2/cda/model/mepo/mepo.d/state/state.py", line 76, in read_state
    raise StateDoesNotExistError('Error! mepo state does not exist')
state.exceptions.StateDoesNotExistError: Error! mepo state does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data2/cda/model/mepo/mepo", line 17, in <module>
    main()
  File "/data2/cda/model/mepo/mepo.d/main.py", line 6, in main
    command.run(args)
  File "/data2/cda/model/mepo/mepo.d/command/command.py", line 11, in run
    cmd_module.run(args)
  File "/data2/cda/model/mepo/mepo.d/command/clone/clone.py", line 61, in run
    mepo_init.run(args)
  File "/data2/cda/model/mepo/mepo.d/command/init/init.py", line 17, in run
    allcomps = MepoState.initialize(args.config,style)
  File "/data2/cda/model/mepo/mepo.d/state/state.py", line 70, in initialize
    complist.append(MepoComponent().to_component(name, comp, directory_style))
  File "/data2/cda/model/mepo/mepo.d/state/component.py", line 97, in to_component
    repo_url = get_current_remote_url()
  File "/data2/cda/model/mepo/mepo.d/state/component.py", line 170, in get_current_remote_url
    output = shellcmd.run(shlex.split(cmd), output=True).strip()
  File "/data2/cda/model/mepo/mepo.d/utilities/shellcmd.py", line 15, in run
    result.check_returncode()
  File "/data2/cda/pkg/miniconda3-4.12.0/envs/cda_suite/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']' returned non-zero exit status 129.
```

**Guess of cause**
The git version of the server is 1.8.3.1, seems to low to have `get-url` command. 

**Go to Try**:
Will install a newer-version git now.

**Comment by gmao-cda** [comment]
Installing lapack-3.10.1 for GEOSgcm build.
MKL not used for GEOSgcm. Is this appropriate? @mathomp4

**Comment by gmao-cda** [comment]
Done. 

It takes me a while to set `LAPACK_LIBABRIES`. Seems I still need to append `blas` static lib into `LAPACK_LIBABRIES` in addition to set `BLAS_LIBRARIES`, otherwise leading to linking error.

total item in `install/bin`: 391 
```
(cda_suite) [cda@measures1 bin]$ ls -al * | wc -l
391`
```

@mathomp4 and @sanAkel , Thank you very much for all your help!

Is there any test data/low-res test run that I can try?

**Comment by sanAkel** [comment]
> Is there any test data/low-res test run that I can try?


yes! Of course, let's get in touch tomorrow with @mathomp4 - as our schedules allow.

**Comment by mathomp4** [comment]
Sorry I missed all that, but it looks like you did well. And, yeah, you had some ancient Git on that system! Oof. I should probably put in some sort of version check in mepo. I guess I forgot Git 1 could even still exist!

And as for test data, yes, I can probably get you some. I'll need to update a public spot we have, but I don't have write access so I'll need to contact someone who does.

Also, I now realize we probably could have had you "rpm install" Intel's compilers and MPI. I keep forgetting they are free now and, well, would have saved you a big GNU and Open MPI build. :/

**Comment by mathomp4** [comment]
Some other things:

> MKL not used for GEOSgcm. Is this appropriate? @mathomp4

MKL is only required to run/compile RRTMGP with GEOS and you won't be doing that. So if it's missing, you just get a warning that RRTMGP can't be run.
 
> It takes me a while to set `LAPACK_LIBABRIES`. Seems I still need to append `blas` static lib into `LAPACK_LIBABRIES` in addition to set `BLAS_LIBRARIES`, otherwise leading to linking error.

And this is interesting. If you had BLAS and LAPACK installed and CMake found it, it should have taken care of the linking for you. Hmm.

**Comment by gmao-cda** [comment]
Thank you very much for your guidance on installing GNU compiler @mathomp4 !
I have never built GNU compiler from src codes, and your detailed and clear guidance makes it trivial.

**Comment by mathomp4** [comment]
@gmao-cda Well, it's a lot of experience doing it. What I do now to not forget is every time I do something like this and make a modulefile for it, I put my instructions at the top a la:

https://github.com/mathomp4/m1modulefiles/blob/main/Compiler/gcc-gfortran-12.1.0/openmpi/4.1.4.lua

Otherwise I'd forget 😄

**Comment by gmao-cda** [comment]
> > It takes me a while to set `LAPACK_LIBABRIES`. Seems I still need to append `blas` static lib into `LAPACK_LIBABRIES` in addition to set `BLAS_LIBRARIES`, otherwise leading to linking error.
> 
> And this is interesting. If you had BLAS and LAPACK installed and CMake found it, it should have taken care of the linking for you. Hmm.

Thanks @mathomp4 , I created a lean blas/lapack test case for to find out why:
1. When I compiled, I used
```
cmake .. -DCMAKE_Fortran_COMPILER=gfortran \
-DBLAS_LIBRARIES=/data2/cda/model/lapack-3.10.1/librefblas.a \
-DLAPACK_LIBRARIES=/data2/cda/model/lapack-3.10.1/liblapack.a
```
where I explicitly assigned `BLAS_LIBRARIES` and `LAPACK_LIBRARIES`, which are the outputs of the `FindBLAS` and `FindLAPACK`.

**This lets FindBLAS, and FindLAPACK skip the internal testing case and find the correct linking flags**, which you can see from cmake output with no `sgemm` test
```
-- The Fortran compiler identification is GNU 12.1.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /data2/cda/pkg/gcc-12.1.0/bin/gfortran - skipped
-- Found BLAS: /data2/cda/model/lapack-3.10.1/librefblas.a
-- Found LAPACK: /data2/cda/model/lapack-3.10.1/liblapack.a
-- Configuring done
-- Generating done
-- Build files have been written to: /data2/cda/model/test/lorenz63_DA-master/src/build
```

2. Then I avoid assigning `BLAS_LIBRARIES` and `LAPACK_LIBRARIES`, and add `CMAKE_LIBRARY_PATH`
```
-- The Fortran compiler identification is GNU 12.1.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /data2/cda/pkg/gcc-12.1.0/bin/gfortran - skipped
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
CMake Error at /data2/cda/libs/cmake-3.24.0/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /data2/cda/libs/cmake-3.24.0/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /data2/cda/libs/cmake-3.24.0/Modules/FindBLAS.cmake:1337 (find_package_handle_standard_args)
  CMakeLists.txt:7 (find_package)
```
Now FindBLAS tries to find the blas lib under `CMAKE_LIBRARY_PATH` but still failed.

This is because for `lapack` downloaded from https://netlib.org/lapack/, the default built lib name with Makefile is `librefblas.a`, which is not recognized by `FindBLAS.cmake` (no `BLA_VENDOR` will leads to `librefblas.a`). Meanwhile, the new CMakeLists.txt 
within the src codes creates `libblas.a`.

3. To solve this, I create a symlink `libblas.a <---librefblas.a`
```
ln -sf /data2/cda/model/lapack-3.10.1/librefblas.a /data2/cda/model/lapack-3.10.1/libblas.a
```
and rerun
```
cmake .. -DCMAKE_Fortran_COMPILER=gfortran \
-DCMAKE_LIBRARY_PATH=/data2/cda/model/lapack-3.10.1
```

Now it works !
```
-- The Fortran compiler identification is GNU 12.1.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /data2/cda/pkg/gcc-12.1.0/bin/gfortran - skipped
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /data2/cda/model/lapack-3.10.1/libblas.a
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /data2/cda/model/lapack-3.10.1/liblapack.a;/data2/cda/model/lapack-3.10.1/libblas.a
-- Configuring done
-- Generating done
-- Build files have been written to: /data2/cda/model/test/lorenz63_DA-master/src/build
```

**Comment by sanAkel** [comment]
@gmao-cda Would you please:
- [ ] Confirm Baselibs are built
- [ ] Model is built

If ⬆️ are ✅ let's close this issue and move on to running the model. Thanks!

**Comment by cd10kfsu** [comment]
Yes. I confirmed

**Comment by sanAkel** [comment]
Thanks! Closing this issue.
